<?php

namespace ArticleBundle\Repository;

/**
 * AmountRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AmountRepository extends \Doctrine\ORM\EntityRepository
{
	public function getAmountsByYear($year, $idStudent)
	{
		$query=$this->getEntityManager()->createQuery('
			SELECT a 
			FROM ArticleBundle:Amount a
			JOIN a.student s
			WHERE a.civilYear = :civilYear
			AND s.id = :idStudent')
		->setParameter('civilYear',$year)
		->setParameter('idStudent',$idStudent);

		return $query->getResult();
	}

	public function getAmounts($year)
	{
		$query=$this->getEntityManager()->createQuery('
			SELECT a 
			FROM ArticleBundle:Amount a 
			WHERE a.civilYear = :civilYear')			
		->setParameter('civilYear',$year);

		return $query->getResult();
	}

	public function getAmountsForStudentCreation($year)
	{
		$qb=$this->createQueryBuilder('q');
		$qb->select('a')
		   ->from('ArticleBundle:Amount','a')
		   ->where('a.civilYear = :civilYear')
		   ->orderBy('a.scholarYear','DESC')
		   ->setParameter('civilYear', $year);

		return $qb;
	}


}
