<?php

namespace ArticleBundle\Repository;

/**
 * AmountPayedRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AmountPayedRepository extends \Doctrine\ORM\EntityRepository
{
	public function getAmountsPayedByStudent($year, $idStudent)
	{
		$query=$this->getEntityManager()->createQuery('
			SELECT ap 
			FROM ArticleBundle:AmountPayed ap 
			JOIN ap.student s
			WHERE s.id = :idStudent
			AND   ap.scholarYear = :scholarYear')
		->setParameter('idStudent', $idStudent)
		->setParameter('scholarYear', $year);

		return $query->getResult();		
	}

	public function getAmountsPayedByStudentAndAmount($idStudent, $idAmount)
	{
		$query=$this->getEntityManager()->createQuery('
			SELECT ap 
			FROM ArticleBundle:AmountPayed ap 			
			WHERE ap.student = :idStudent
			AND ap.amount = :idAmoun')
		->setParameter('idStudent', $idStudent)
		->setParameter('idAmoun', $idAmount);

		return $query->getResult();		
	}
}
