<?php

namespace ArticleBundle\Repository;

/**
 * ArchivedFeesStudentRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ArchivedFeesStudentRepository extends \Doctrine\ORM\EntityRepository
{
}
