<?php

namespace ArticleBundle\Repository;

/**
 * ArticleRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ArticleRepository extends \Doctrine\ORM\EntityRepository
{
	public function countArticles()
	{
		$query=$this->getEntitymanager()->createQuery('
			SELECT COUNT(a.id)
			FROM ArticleBundle:Article a
			WHERE a.origin = 6');

		return $query->getSingleScalarResult();		
	}	

	public function articlesHomepage()
	{
		$query=$this->getEntitymanager()->createQuery('
			SELECT a 
			FROM ArticleBundle:Article a 
			WHERE a.selected = 1
			AND a.origin = 6
			ORDER BY a.dateCreated DESC')
		->setMaxResults(3);

		return $query->getResult();
	}

	public function articlesAdminHomepage()
	{
		$query=$this->getEntitymanager()->createQuery('
			SELECT a 
			FROM ArticleBundle:Article a 
			WHERE a.selected = 1
			AND a.origin = 6
			ORDER BY a.dateCreated DESC');

		return $query->getResult();
	}

	public function listArticles()
	{
		$query=$this->getEntitymanager()->createQuery('
			SELECT a 
			FROM ArticleBundle:Article a 			
			WHERE a.origin = 6
			ORDER BY a.dateCreated ASC');

		return $query->getResult();
	}

	public function getArticlesForActivities($origin)
	{
		$query=$this->getEntitymanager()->createQuery('
			SELECT a 
			FROM ArticleBundle:Article a 			
			WHERE a.origin = :origin
			ORDER BY a.dateCreated DESC')
		->setParameter('origin', $origin);

		return $query->getResult();
	}
}
