<?php

namespace ArticleBundle\Repository;

/**
 * BookRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class BookRepository extends \Doctrine\ORM\EntityRepository
{
	public function countBook()
	{
		$query=$this->getEntityManager()->createQuery('
			SELECT COUNT(b.id)
			FROM ArticleBundle:Book b');

		return $query->getSingleScalarResult();
	}

	public function countBookAvailable()
	{
		$query=$this->getEntityManager()->createQuery('
			SELECT COUNT(b.id)
			FROM ArticleBundle:Book b
			WHERE b.available = 1');

		return $query->getSingleScalarResult();
	}

	public function countBookUnAvailable()
	{
		$query=$this->getEntityManager()->createQuery('
			SELECT COUNT(b.id)
			FROM ArticleBundle:Book b
			WHERE b.available = 0');

		return $query->getSingleScalarResult();
	}	
}
