<?php

namespace ArticleBundle\Repository;

/**
 * BoursierRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class BoursierRepository extends \Doctrine\ORM\EntityRepository
{
}
