<?php

namespace ArticleBundle\Repository;

/**
 * DocumentRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DocumentRepository extends \Doctrine\ORM\EntityRepository
{
	public function getDocumentsByUser($id)
	{
		$query=$this->getEntityManager()->createQuery('
			SELECT d 
			FROM ArticleBundle:Document d
			JOIN d.user u
			WHERE u.id = :idUser')
		->setParameter('idUser', $id);

		return $query->getResult();
	}	
}
