<?php

namespace ArticleBundle\Repository;

/**
 * MailSendedRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MailSendedRepository extends \Doctrine\ORM\EntityRepository
{
}
