<?php

namespace ArticleBundle\Repository;

/**
 * StudentRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class StudentRepository extends \Doctrine\ORM\EntityRepository
{
	public function countStudents()
	{
		$query=$this->getEntityManager()->createQuery('
			SELECT COUNT(s.id)
			FROM ArticleBundle:Student s
			WHERE s.archived =1');

		return $query->getSingleScalarResult();
	}
}
