<?php

namespace ArticleBundle\Repository;

/**
 * YearSchoolRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class YearSchoolRepository extends \Doctrine\ORM\EntityRepository
{
}
