<?php

namespace UserBundle\Repository;

/**
 * UserRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UserRepository extends \Doctrine\ORM\EntityRepository
{
	public function countBoursiers()
	{
		$query=$this->getEntityManager()->createQuery('
			SELECT COUNT(b.id) 
			FROM UserBundle:User b
			WHERE b.roles = :roleuser')
		->setParameter('roleuser', 'ROLE_USER');

		return $query->getSingleScalarResult();
	}

	public function getAdmin()
	{
		$query=$this->getEntityManager()->createQuery('
			SELECT b
			FROM UserBundle:User b
			WHERE b.roles != :roleAdmin')
		->setParameter('roleAdmin', 'ROLE_ADMIN');

		return $query->getResult();
	}	
	
}
